const express=require('express');
const router=express.Router();
const sujetRouter=require('./sujets');
const userRouter=require('./users');
const subscriptionController = require('../controllers/subscriptionController');
const question_awnserRouter=require('./question_awnser');
const sujetBySubscriptionController = require('../controllers/sujetBySubscriptionController');
router.use("/sujets",sujetRouter);
router.use("/question_awnser",question_awnserRouter);
router.use('/users',userRouter);
router.post('/users/:userId/subscriptions', subscriptionController.createSubscription);
router.put('/users/:userId/subscriptions/cancel', subscriptionController.cancelSubscription);
router.get('/users/:userId/sujets', sujetBySubscriptionController.getSujetsBySubscription);
module.exports=router;